# 配置文件

DAILY_TIME: "00:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-02-07" # 纪念日
CITY: "深圳"

BIRTHDAY:
  - "09-29"

APP_ID: "wxe539970068531b83  "
APP_SECRET: "449bb316c1071e62c89ae145bd0f386b"

USER_ID: 
  - "o9hZR6afzU0nLk2Oa4EOEhIXj84E"
TEMPLATE_ID: "xKx46rscdid3K1BI7T6MIAAQyg9m0nzLdpuZpJBrlY4"
